import anyTest, { TestFn } from "ava";
import { NearAccount, Worker } from "near-workspaces";
import { daysToMs } from "./utils";
import ECPairFactory, { ECPairInterface } from "ecpair";
import { RegtestUtils } from "regtest-client";
import * as ecc from "tiny-secp256k1";
import { compressPubKey, deriveAddress } from "./btc";
import "dotenv/config";
import {
  fastForward,
  setCurrentAccountId,
  syncChainSignaturesRootPubkey,
  V1_PK_PATH,
} from "./bithive";

const ECPair = ECPairFactory(ecc);

export function initUnit(sandbox = true) {
  const test = anyTest as TestFn<{
    worker: Worker;
    accounts: Record<string, NearAccount>;
    aliceKeyPair: ECPairInterface;
    bobKeyPair: ECPairInterface;
    bithivePubkey: Buffer;
  }>;

  test.beforeEach(async (t) => {
    // --
    // near sandbox related
    if (sandbox) {
      // Init the worker and start a Sandbox server
      const worker = await Worker.init();
      // Create accounts
      const root = worker.rootAccount;
      const fixtures = await createFixtures(root);
      t.context.worker = worker;
      t.context.accounts = {
        root,
        ...fixtures,
      };
    }

    // btc
    const aliceKeyPair = ECPair.makeRandom();
    const bobKeyPair = ECPair.makeRandom();
    const bithivePkUncompressed = (
      await deriveAddress("bithive.test.near", V1_PK_PATH, "testnet")
    ).publicKey;
    const bithivePubkey = compressPubKey(bithivePkUncompressed);

    t.context.aliceKeyPair = aliceKeyPair;
    t.context.bobKeyPair = bobKeyPair;
    t.context.bithivePubkey = bithivePubkey;
  });

  test.afterEach.always(async (t) => {
    if (!sandbox) return;
    // Stop Sandbox server
    await t.context.worker.tearDown().catch((error) => {
      console.log("Failed to stop the Sandbox:", error);
    });
  });

  return test;
}

export function initIntegration() {
  const test = anyTest as TestFn<{
    worker: Worker;
    accounts: Record<string, NearAccount>;
    keyPairs: Record<string, ECPairInterface>;
    regtestUtils: RegtestUtils;
    bithivePubkey: Buffer;
    nearTestnetAccountId: string;
  }>;

  // since tests could run in parallel, be careful when calling regtestUtils because
  // they can overlap with each other
  const regtestUtils = new RegtestUtils({ APIURL: "http://localhost:8080/1" });

  test.beforeEach(async (t) => {
    // Init the worker and start a Sandbox server
    const worker = await Worker.init();

    // --
    // contract related

    // Create accounts
    const root = worker.rootAccount;
    const fixtures = await createFixtures(root);

    // --
    // btc related
    // hardcode every key so that the mocked chain signatures can produce the correct result
    const aliceKeyPair = ECPair.makeRandom();
    console.log("alice    pubkey", aliceKeyPair.publicKey.toString("hex"));

    const nearTestnetAccountId = process.env.TESTNET_ACCOUNT_ID;
    if (!nearTestnetAccountId) {
      throw new Error("missing env TESTNET_ACCOUNT_ID");
    }

    // this is to make sure the derived bithive pubkey matches
    // the actual signature generated by nearTestnetAccountId
    await setCurrentAccountId(fixtures.contract, nearTestnetAccountId);

    const bithivePkUncompressed = (
      await deriveAddress(nearTestnetAccountId, V1_PK_PATH, "testnet")
    ).publicKey;
    const bithivePubkey = compressPubKey(bithivePkUncompressed);

    t.context.worker = worker;
    t.context.accounts = {
      root,
      ...fixtures,
    };
    t.context.keyPairs = {
      alice: aliceKeyPair,
    };
    t.context.regtestUtils = regtestUtils;
    t.context.bithivePubkey = bithivePubkey;
    t.context.nearTestnetAccountId = nearTestnetAccountId;
  });

  test.afterEach(async (t) => {
    // Stop Sandbox server
    await t.context.worker.tearDown().catch((error) => {
      console.log("Failed to stop the Sandbox:", error);
    });
  });

  return test;
}

async function createFixtures(root: NearAccount) {
  const owner = await root.createSubAccount("owner");
  const alice = await root.createSubAccount("alice");

  const mockLightclient = await deployAndInit({
    root,
    subContractId: "light-client",
    code: "res/mock_btc_light_client.wasm",
    init: {
      methodName: "init",
      args: {},
    },
  });

  const mockChainSignature = await deployAndInit({
    root,
    subContractId: "chain-sig",
    code: "res/mock_chain_signatures.wasm",
    init: {
      methodName: "init",
      args: {},
    },
  });

  const mockBip322Verifier = await deployAndInit({
    root,
    subContractId: "bip322-verifier",
    code: "res/bip322_verifier_test.wasm",
    init: {
      methodName: "new",
      args: {},
    },
  });

  const contract = await deployAndInit({
    root,
    subContractId: "bithive",
    code: "res/bithive_test.wasm",
    init: {
      methodName: "init",
      args: {
        args: {
          owner_id: owner.accountId,
          btc_light_client_id: mockLightclient.accountId,
          bip322_verifier_id: mockBip322Verifier.accountId,
          chain_signatures_id: mockChainSignature.accountId,
          n_confirmation: 6,
          withdrawal_waiting_time_ms: daysToMs(2),
          min_deposit_satoshi: 100,
          earliest_deposit_block_height: 0,
          solo_withdrawal_seq_heights: [5],
        },
      },
    },
  });
  await syncChainSignaturesRootPubkey(contract);

  // make sure the timestamp is not 0 at first
  await fastForward(contract, daysToMs(3));

  return {
    owner,
    alice,
    contract,
    mockChainSignature,
    mockLightclient,
  };
}

async function deployAndInit({
  root,
  subContractId,
  code,
  init,
  initialBalance,
}: {
  root: NearAccount;
  subContractId: string;
  code: Uint8Array | string;
  init?: {
    methodName: string;
    args?: Record<string, unknown>;
  };
  initialBalance?: string;
}): Promise<NearAccount> {
  const contract = await root.createSubAccount(subContractId, {
    initialBalance,
  });
  const result = await contract.deploy(code);
  if (result.failed) {
    throw result.Failure;
  }
  if (init) {
    await contract.call(contract, init.methodName, init.args ?? {});
  }
  return contract;
}
