name: Build Contract

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install necessary dependencies
      - name: Install Rust and dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Build the project
      - name: Build the project
        run: make btc-client

      # Step 4: Archive the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-artifacts
          path: ./res
          retention-days: 30
