name: Build Contract

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project
        run: make btc-client

      - name: Set artifact name
        id: set_name
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            TAG_NAME="latest"
          fi
          echo "artifact_name=build-artifacts-${TAG_NAME}" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ./res
          retention-days: 30
